@extends('layouts.appMaxwell')
@section('content')
    <div style="height:0px;width:0px;overflow:hidden;-webkit-margin-top-collapse: separate;"></div>
    <div class="ttr_business-growth_html_row0 row">
        <div class="post_column col-lg-12 col-md-10 col-sm-10 col-xs-9">
            <div class="ttr_business-growth_html_column00">
                <div style="height:0px;width:0px;overflow:hidden;-webkit-margin-top-collapse: separate;"></div>
                <div class="html_content"><p style="margin:0.12em 0em 0em 0em;"><span style="font-family:'Open Sans','Arial';font-weight:300;">Our team will work closely with your team to connect your firm and advisors to our services and solufions to drive asset growth and client loyalty.</span></p><p style="margin:0.12em 0em 0em 0em;"><span></span></p><p style="margin:0.12em 0em 0em 0em;"><span style="font-family:'Open Sans','Arial';font-weight:300;font-size:1.5em;">Individual Investors</span></p><p style="margin:0.31em 0em 0.31em 0em;"><span style="font-family:'Open Sans','Arial';font-weight:300;">Our firm has developed a simple and effective platform that will work not only for institutional investments or corporation, but also for individual investrs. We will help your advisors to identify and prioritize financial and life goals and create a plan around it With professional and easy to understand tools, you are sure that your advisors can confidently assist clients on what matters most to them.</span></p><p style="margin:0.31em 0em 0.31em 0em;"><span></span></p><p style="margin:0.31em 0em 0.31em 0em;"><span style="font-family:'Open Sans','Arial';font-weight:300;font-size:1.5em;">New Client Acquisition</span></p><p style="margin:0.31em 0em 0.31em 0em;"><span style="font-family:'Open Sans','Arial';font-weight:300;">We believe that advisor tools should be simple, effective, and truly modern. Therefore, we created a platform that promotes advisor-client relationship. It is a single sign on tool that has everything an advisor needs. This gives our clients peace of mind, developing more efficient practices and creating deeper client relationships.</span></p><p style="margin:0.31em 0em 0.31em 0em;"><span style="font-family:'Open Sans','Arial';font-weight:300;">Aside from our advisor tools, your advisors will have a team of professionals that will back them up, and help them in making the transition to this new process simple and easy. Your advisors will be able to focus their strength to an advice focused business model.Stienberg Trade Holdings aim to provide our clients with all the business support and services that they need to create an efficient, professional, and reliable process for them to be able to operate the business with ease and enable them to focus on what's important --- growing a profitable and stable client base.</span></p><p><br style="font-family:'Open Sans','Arial';font-weight:300;" /></p></div>
                <div style="height:0px;width:0px;overflow:hidden;-webkit-margin-top-collapse: separate;"></div>
                <div style="clear:both;"></div>
            </div>
        </div>
        <div class=" visible-lg-block" style="clear: both;"></div>
    </div>
    <div style="height:0px;width:0px;overflow:hidden;-webkit-margin-top-collapse: separate;"></div>
@endsection
